/**
 * principles.md — derived from `philosophy`.
 *
 * Sections:
 *   - Mission (philosophy.mission)
 *   - Do (philosophy.principles[])
 *   - Don't (philosophy.antiPrinciples[])
 *
 * Pure function: same Brief → same Markdown.
 */
import type { Brief } from "../brief.js";

export function renderPrinciples(brief: Brief): string {
    const { mission, principles, antiPrinciples } = brief.philosophy;
    const lines: string[] = [];

    lines.push("## Mission", "", mission, "");

    lines.push("## Do");
    lines.push("");
    if (principles.length === 0) {
        lines.push("_(no principles declared in the Brief)_");
    } else {
        for (const p of principles) lines.push(`- ✓ ${p}`);
    }
    lines.push("");

    lines.push("## Don't");
    lines.push("");
    if (!antiPrinciples || antiPrinciples.length === 0) {
        lines.push("_(no anti-principles declared in the Brief)_");
    } else {
        for (const p of antiPrinciples) lines.push(`- ✗ ${p}`);
    }
    lines.push("");

    lines.push(
        "## How to use this document",
        "",
        "These principles are the **single source of truth** for design and",
        "implementation decisions. When in doubt, choose the option that better",
        "honors the Do list and avoids the Don't list. Update the Brand Brief",
        "(`brief.yaml > philosophy`) and regenerate — do not edit this file.",
        "",
    );

    return lines.join("\n");
}
